server:
  port: 16002
  servlet:
    context-path: /client/api/v1
    session:
      cookie:
        name: gSESSIONID
spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://galaxy.jd.local/oauth2/oauth/token
      userAuthorizationUri: http://galaxy.jd.local/oauth2/oauth/authorize
    resource:
      userInfoUri: http://galaxy.jd.local/oauth2/whoami
      
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"